version: "2"

services:

#
# Webserver
#           
  webserver:
    build:
      context: .docker/apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    ports:
      - "${WEBSERVER_EXPOSED_PORT}:80"
    #   - "${WEBSERVER_SSL_EXPOSED_PORT}:443"
    environment:
      - WEBSERVER_EXPOSED_PORT=${WEBSERVER_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    volumes:
      - ${PROJECT_SOURCE_PATH}:${PHP_APP_DIR}
      - ./logs/apache:${APACHE_ROOT_DIR}/logs
    networks:
      public_net:


#
# Application
#         
  app_identity_provider:
    build:
      context: .docker
      dockerfile: php-debug/Dockerfile
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - XDEBUG_PORT=${XDEBUG_PORT}
    working_dir: ${PHP_APP_DIR}
    depends_on:
      - webserver
    volumes:
      - ${PROJECT_SOURCE_PATH}:${PHP_APP_DIR}
    environment:
      - WEBSERVER_EXPOSED_PORT=${WEBSERVER_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - XDEBUG_PORT=${XDEBUG_PORT}
    networks:
      public_net:


networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}